import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import SignInBtn from "./signInBtn";
import SignOutBtn from "./signOutBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  //서버 컴포넌트에서 로그인된 유저정보 출력
  let session = await getServerSession(authOptions)
  // console.log(user)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar"> 
        <Link href="/" className="logo">Appleforum</Link>
        <Link href="/list">List</Link>
        {
          session ?  <Link href="/write" >글쓰기</Link> : <div></div>
        }
        {
          !session ? <SignInBtn></SignInBtn> : <SignOutBtn></SignOutBtn>
        }
      </div>  
        {children}
      </body>
    </html>
  );
}
