import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import SignInBtn from "./signInBtn";
import SignOutBtn from "./signOutBtn";
import DarkModeOnBtn from "./darkModeOnBtn";
import { cookies } from "next/headers"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  //서버 컴포넌트에서 로그인된 유저정보 출력
  let session = await getServerSession(authOptions)
  // console.log(user)

  let res =  (await cookies()).get('darkMode')
  let currentCookie = res ? res.value : 'off'

  let className = (res != undefined && res.value == 'on') ? 'dark-mode' : 'light-mode'
  return (
    <html lang="en">
      <body className= {className} >
      <div className="navbar" > 
        <Link href="/" className="logo">forum</Link>
        <Link href="/list">List</Link>
        {
          session ?  <Link href="/write" >글쓰기</Link> : <div></div>
        }
        {
        !session ? <span><SignInBtn></SignInBtn></span> : <span><SignOutBtn></SignOutBtn></span>
        }
        <DarkModeOnBtn currentCookie={currentCookie}/>
      </div>
        {children}
      </body>
    </html>
  );
}
