import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import SignInBtn from "./signInBtn";
import SignOutBtn from "./signOutBtn";
import DarkModeOnBtn from "./darkModeOnBtn";
import { cookies } from "next/headers"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MHhub",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  //서버 컴포넌트에서 로그인된 유저정보 출력
  let session = await getServerSession(authOptions)
  // console.log(user)

  let res =  (await cookies()).get('darkMode')
  let currentCookie = res ? res.value : 'off'

  let className = (res != undefined && res.value == 'on') ? 'dark-mode' : 'light-mode'
  return (
    <html lang="en">
      <body className= {className} >
      <div className="navbar">
          {/* ✅ 왼쪽 링크 (로고 & 리스트,글쓰기) */}
          <div className="left-links">
              <Link href="/" className="logo">명훈 게시판</Link>
              <Link href="/list">자유게시판</Link>
              {session && <Link href="/write">글쓰기</Link>}
          </div>

          {/* ✅ 오른쪽 버튼 컨테이너 */}
          <div className="right-buttons">
              {!session ? <SignInBtn /> : <SignOutBtn />}
              <DarkModeOnBtn currentCookie={currentCookie} />
          </div>
      </div>
        {children}
      </body>
    </html>
  );
}
